<?php
/* Generated by neoan3-cli */

namespace Neoan3\Components;

use Neoan3\Apps\Ops;
use Neoan3\Apps\Session;
use Neoan3\Apps\Stateless;
use Neoan3\Core\RouteException;
use Neoan3\Core\Unicore;
use Neoan3\Frame\Neoan;
use PHPMailer\PHPMailer\Exception;

class ContactUs extends Neoan {
    private $uniCore;

    function init() {
        $this->uniCore = new Unicore();
        $this->uniCore->uni('neoan')
                      ->callback($this, 'vue')
                      ->callback($this, 'session')
                      ->hook('main', 'contactUs')
                      ->output();
    }

    /**
     * @param Neoan $uni
     */
    function vue($uni){
        $uni->vueComponent('contactUs');
    }
    /**
     * @param Neoan $uni
     */
    function session($uni){
        $hash = Ops::hash(5);
        Session::add_session(['contact_hash'=>$hash]);
        $uni->js .= 'let contactHash = "' . $hash .'";';
    }

    function postContactUs($info) {
        if(!isset($_SESSION['contact_hash']) || !isset($info['contactHash']) || $info['contactHash'] != $_SESSION['contact_hash']){
            throw new RouteException('unauthorized', 401);
        }
        $mail = $this->newMail();
        try {
            // to
            $mail->setFrom($mail->Username, 'Neoan3');
            $mail->addAddress($mail->Username);

            // content
            $mail->isHTML(false);
            $mail->Subject = 'Contact form: '. $info['topic'];
            $mail->Body = $info['email'] ."\n\n".$info['body'];
            $mail->send();
        } catch (Exception $e) {
            return ['success'=>false,'error'=>$e->getMessage()];
        }
        return ['success'=>true];
    }

}
