<?php
/* Generated by neoan3-cli */

namespace Neoan3\Components;

use Neoan3\Frame\Neoan;

class ProfileSettings extends Neoan {
    function getProfileSettings($obj){
        
    }

    function postProfileSettings($obj){
        
    }

}
