<?php
/* Generated by neoan3-cli */

namespace Neoan3\Components;

use Neoan3\Apps\Stateless;
use Neoan3\Frame\Neoan;
use Neoan3\Model\MetricsModel;

class Metric extends Neoan
{
    function getMetric(array $body)
    {
        if (isset($body['slug'])) {
            return MetricsModel::visits(parse_url(base)['path'] . '/article/' . $body['slug']);
        }
    }


}
