<?php
/* Generated by neoan3-cli */

namespace Neoan3\Components;

use Neoan3\Core\Unicore;
use Neoan3\Frame\Neoan;

class Home extends Unicore {
    function init() {
        $this->uni('neoan')
             ->addHead('title', 'blua.blue - CMS')
             ->hook('main', 'home')
             ->callback($this,'loadComponent')
             ->output();
    }

    /**
     * @param Neoan $uni
     */
    function loadComponent($uni){

        $uni->vueComponent('login');
    }

}
