<?php
/* Generated by neoan3-cli */

namespace Neoan3\Components;

use Neoan3\Core\Serve;
use Neoan3\Core\Unicore;
use Neoan3\Frame\Neoan;

class Home extends Unicore {
    function init() {
        $this->uni('neoan')
             ->hook('main', 'home')
             ->callback($this,'loadComponent')
             ->output();
    }

    /**
     * @param Serve $uni
     */
    function loadComponent($uni){
        $this->vueComponent($uni,'login');
        $uni->js .= "new Vue({el:'#home-page'});";
    }
    private function vueComponent($context, $element, $params = []) {
        $params['base'] = base;
        $path = path . '/component/' . $element . '/' . $element . '.ce.';
        if (file_exists($path . $context->viewExt)) {
            $context->footer .= '<template id="' . $element . '">' .
                $context->fileContent($path . $context->viewExt, $params) .
                '</template>';
        }
        if (file_exists($path . 'js')) {
            $context->js .= $context->fileContent($path . 'js', $params);
        }

        return $context;
    }

}
