<?php
/* Generated by neoan3-cli */

namespace Neoan3\Components;

use Neoan3\Apps\Db;
use Neoan3\Apps\Ops;
use Neoan3\Apps\Session;
use Neoan3\Apps\Stateless;
use Neoan3\Core\RouteException;
use Neoan3\Core\Unicore;
use Neoan3\Frame\Neoan;
use Neoan3\Model\UserModel;

class Profile extends Unicore {
    private $components = ['uploadImage', 'articleList', 'profileSettings', 'profile'];
    function init() {
        $this->uni('neoan')
             ->callback($this, 'secure')
             ->callback($this, 'components')
             ->includeElement('profile')
             ->hook('main', 'profile')
             ->output();
    }

    /**
     * @param Neoan $frame
     */
    function components($frame) {
        foreach ($this->components as $component){
            $frame->vueComponent($component);
        }

    }

    function secure($uni) {
        Session::restricted();
    }
    private function asApi(){
        new Neoan();
    }
    function putProfile($user){
        $this->asApi();
        $jwt = Stateless::restrict();
        $userModel = UserModel::byId($jwt['jti']);
        // compare
        // 1. Email
        if($user['email']['email'] !== $userModel['email']['email'] || empty($userModel['email']['confirm_date'])){
            Db::user_email(['delete_date'=>'.'],['user_id'=>'$'.$userModel['id']]);
            $hash = Ops::randomString(30);
            Db::ask('user_email',[
                'user_id'=>'$'.$userModel['id'],
                'email'=>$user['email']['email'],
                'confirm_code'=>$hash
            ]);
            $verify = new Verify();
            $trySending = $verify->confirmEmail($user['email']['email'],$hash);
            if(!$trySending['success']){
                throw new RouteException('Email could not be sent',500);
            }
        }
        // Profile pic
        if($user['image_id'] !== $userModel['image_id']){
            Db::user(['image_id'=>'$'.$user['image_id']],['id'=>'$'.$userModel['id']]);
        }

    }

}
