<?php
/* Generated by neoan3-cli */

namespace Neoan3\Components;

use Neoan3\Core\Unicore;

class Admin extends Unicore {
    function init() {
        $this->uni('neoan')
            ->vueComponent('categories')
            ->vueComponent('admin')
             ->hook('main', 'admin')
             ->output();
    }

}
