<?php
/* Generated by neoan3-cli */

namespace Neoan3\Components;

use Neoan3\Apps\Db;
use Neoan3\Apps\Stateless;
use Neoan3\Frame\Neoan;
use Neoan3\Model\IndexModel;
use Neoan3\Model\UserModel;

class Users extends Neoan {
    function getUsers($obj) {
        $jwt = Stateless::restrict('admin');
        $response = ['users' => [], 'total' => 0];
        $start = isset($obj['skip']) ? $obj['skip'] : 0;
        $limit = isset($obj['top']) ? $obj['top'] : 20;
        $response['total'] = (int) IndexModel::first(
            Db::ask('>SELECT COUNT(*) as total FROM user WHERE delete_date IS NULL')
        )['total'];
        $users = Db::easy('user.id', ['^delete_date'], ['limit' => [$start, $limit]]);
        foreach ($users as $user) {
            $response['users'][] = UserModel::byId($user['id']);
        }
        return $response;
    }

    function postUsers($obj) {

    }

}
