<?php
/* Generated by neoan3-cli */

namespace Neoan3\Components;

use Neoan3\Apps\Db;
use Neoan3\Apps\Stateless;
use Neoan3\Core\RouteException;
use Neoan3\Frame\Neoan;

class Comment extends Neoan
{

    /**
     * @param array $body
     *
     * @return array
     * @throws RouteException
     * @throws \Neoan3\Apps\DbException
     */
    function postComment(array $body)
    {
        $jwt = Stateless::restrict('user');
        if(isset($body['articleId']) && isset($body['comment'])){
            $id = Db::uuid()->uuid;
            Db::article_comment([
                'id' => '$' . $id,
                'article_id' => '$' . $body['articleId'],
                'user_id' => '$' . $jwt['jti'],
                'comment' => '=' . $body['comment']
            ]);
            return ['id'=>$id];
        }
        throw new RouteException('Bad data',400);
    }

}
