<?php
/* Generated by neoan3-cli */

namespace Neoan3\Frame;

use Neoan3\Core\Serve;

class Blua extends Serve {
    function constants() {
        return [
            'base' => [base],
            'link' => [
                [
                    'sizes' => '32x32',
                    'type' => 'image/png',
                    'rel' => 'icon',
                    'href' => 'asset/img/blua-blue-icon-32x32.png'
                ]
            ],
            'meta' => [
                ['name' => 'viewport', 'content' => 'width=device-width, initial-scale=1']
            ],
            'js' => [
                ['src' => 'https://use.fontawesome.com/releases/v5.3.1/js/all.js'],
                ['src' => base . 'node_modules/vue/dist/vue.js'],
                ['src' => base . 'node_modules/axios/dist/axios.min.js'],
                ['src' => base . 'node_modules/lodash/lodash.min.js'],
                ['src' => path . '/frame/neoan/axios-wrapper.js', 'data' => ['base' => base]],
            ],
            'stylesheet' => [
                '' . base . 'frame/neoan/main.css'
            ]
        ];
    }
}
