<?php
/* Generated by neoan3-cli */

namespace Neoan3\Components;

use Neoan3\Frame\Neoan;

class Developer extends Neoan
{
    private $vueElements = ['login', 'developer'];
    function init()
    {
        foreach ($this->vueElements as $vueElement){
            $this->vueComponent($vueElement);
        }
        $this->hook('main','developer')->output();
    }

}
