<?php
/* Generated by neoan3-cli */

namespace Neoan3\Model;


use Neoan3\Apps\Db;
use Neoan3\Apps\Ops;
use Neoan3\Apps\Session;

/**
 * Class WebhookTransformer
 * @package Neoan3\Model
 */
class WebhookTransformer implements IndexTransformer
{

    /**
     * @param $input
     *
     * @return string
     * @throws \Exception
     */
    static function userId($input)
    {
        $userId = false;
        if ($input) {
            $userId = '$' . $input;
        } elseif (Session::is_logged_in()) {
            $userId = '$' . Session::user_id();
        }
        if ($userId) {
            return $userId;
        } else {
            throw new \Exception('No user id');
        }
    }

    /**
     * @param bool $givenId
     *
     * @return array
     * @throws \Neoan3\Apps\DbException
     */
    static function modelStructure($givenId = false)
    {
        $mainId = $givenId ? $givenId : Db::uuid()->uuid;
        return [

            'id' => [
                'on_creation' => function () use ($mainId) {
                    return '$' . $mainId;
                }
            ],
            'user_id' => [
                'on_creation' => function ($input) {

                    return self::userId($input);
                }
            ],
            'target_url' => [
                'required' => true
            ],
            'token' => [
                'on_creation' => function ($input) {
                    $token = $input ? $input : Ops::randomString(18);
                    return $token;
                }
            ]

        ];
    }
}
