<?php
/* Generated by neoan3-cli */

namespace Neoan3\Model;


use Neoan3\Apps\Transformer;

/**
 * Class WebhookModel
 *
 * @method static find($array)
 * @method static delete($array)
 * @method static create($array)
 * @method static update($array)
 * @package Neoan3\Model
 */
class WebhookModel extends IndexModel
{
    static function __callStatic($name, $arguments)
    {
        return Transformer::addMagic($name,$arguments);
    }

}
