<?php
/* Generated by neoan3-cli */

namespace Neoan3\Model;


use Neoan3\Apps\SimpleTracker;

/**
 * Class MetrixModel
 * @package Neoan3\Model
 */
class MetricsModel extends IndexModel
{
    /**
     * @param bool $endpoint
     *
     * @return array
     */
    static function visits($endpoint = false)
    {
        $visitors = [];
        $visits = SimpleTracker::endpointData($endpoint)
                               ->toArray();
        if (isset($visits['visits'])) {
            $visits = $visits['visits'];
        }
        foreach ($visits as $visit) {
            if (!in_array($visit['identifier'], $visitors)) {
                $visitors[] = $visit['identifier'];
            }
        }
        return [
            'total' => count($visits),
            'unique' => count($visitors)
        ];
    }


}

