<?php
/* Generated by neoan3-cli */

namespace Neoan3\Components;

use Neoan3\Apps\Db;
use Neoan3\Apps\Session;
use Neoan3\Apps\Stateless;
use Neoan3\Frame\Neoan;
use Neoan3\Model\IndexModel;
use Neoan3\Model\UserModel;
use PHPMailer\PHPMailer\Exception;

class Verify extends Neoan {
    function init(){
        if(!sub(1) || !isset($_GET['email'])){
            exit();
        }
        $user = IndexModel::first(UserModel::find(['user_email.email'=>$_GET['email'],'user_email.delete_date'=>'']));
        if(empty($user)){
            exit();
        }

        $unconfirmedEmail = IndexModel::first(Db::easy('user_email.id user_email.confirm_code',['user_id'=>'$'.$user['id'],'^delete_date','^confirm_date']));

        if(!empty($unconfirmedEmail) &&$unconfirmedEmail['confirm_code'] == sub(1) ){
            Db::user_email(['confirm_date'=>'.'],['id'=>'$'.$unconfirmedEmail['id']]);
            Session::logout();
            redirect('profile/#settings');
        } else {
            echo "Invalid url";

        }
        exit();
    }
    function confirmEmail($to, $hash) {
        $link = base . 'verify/'.$hash.'/?email='.$to;
        $mail = $this->newMail();
        try {
            // to
            $mail->setFrom('neoan@neoan.us', 'Neoan3');
            $mail->addAddress($to);

            // content
            $mail->isHTML(false);
            $mail->Subject = 'Email confirmation request';
            $mail->Body = 'We are still working on our emails. Meanwhile, please visit the following link to verify your email: '.$link;
            $mail->send();
        } catch (Exception $e) {
            return ['success'=>false,'error'=>$e->getMessage()];
        }
        return ['success'=>true];
    }


}
