<?php
/* Generated by neoan3-cli */

namespace Neoan3\Components;

use Neoan3\Apps\Db;
use Neoan3\Apps\Session;
use Neoan3\Apps\Stateless;
use Neoan3\Frame\Neoan;
use Neoan3\Model\IndexModel;
use Neoan3\Model\UserModel;
use PHPMailer\PHPMailer\Exception;

class Verify extends Neoan {
    function init(){
        if(!sub(1) || !isset($_GET['email'])){
            exit();
        }

        $user = IndexModel::first(UserModel::findEmails(['email'=>$_GET['email']]));
        if(empty($user)){
            exit();
        }
        $unconfirmedEmail = [];
        foreach($user['emails'] as $email){
            if($email['email'] == $_GET['email'] && empty($email['confirm_date']) && $email['confirm_code'] == sub(1)){
                $unconfirmedEmail = $email;
            }
        }
        if(!empty($unconfirmedEmail) && $unconfirmedEmail['confirm_code'] == sub(1) ){
            Db::user_email(['confirm_date'=>'.'],['id'=>'$'.$unconfirmedEmail['id']]);
            Session::logout();
            redirect('profile/#settings');
        } else {
            echo "Invalid url";

        }
        exit();
    }
    function confirmEmail($to, $hash) {
        $link = base . 'verify/'.$hash.'/?email='.$to;
        $content = '<p>In order to activate your account, please use the following link:</p>';
        $content .= '<a href="'.$link.'" style="color:#aaaaaa">'.$link.'</a>';

        $mail = new Email('Email confirmation request','Welcome to blua.blue',$content);
        try {
            $mail->mailer->addAddress($to);
            $mail->mailer->send();
        } catch (Exception $e) {
            return ['success'=>false,'error'=>$e->getMessage()];
        }
        return ['success'=>true];
    }


}
